---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}${SUFFIX}
objects:

- kind: Secret
  apiVersion: v1
  metadata:
    name: ${NAME}${SUFFIX}
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
  stringData:
    keycloak-url: ${KEYCLOAK_AUTHSERVERURL}
    keycloak-realm: ${KEYCLOAK_REALM}
    keycloak-clientId: ${KEYCLOAK_CLIENTID}
  type: Opaque

- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}${SUFFIX}
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
  spec:
    ports:
    - name: ${NAME}
      port: ${{PORT}}
      protocol: TCP
      targetPort: ${{PORT}}
    selector:
      name: ${NAME}${SUFFIX}

- kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}${SUFFIX}
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: ${NAME}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
      weight: 100

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${NAME}${SUFFIX}
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
  spec:
    replicas: 1
    selector:
      name: ${NAME}${SUFFIX}
    strategy:
      type: Rolling
    template:
      metadata:
        name: ${NAME}${SUFFIX}
        labels:
          name: ${NAME}${SUFFIX}
          app: ${APP_NAME}${SUFFIX}
          app-group: ${APP_GROUP}
      spec:
        containers:
        - name: ${NAME}${SUFFIX}
          env:
          - name: APP_KEY
            value: ${APP_KEY}
          - name: API_KEY
            value: ${API_KEY}
          - name: APP_DEBUG
            value: ${APP_DEBUG}
          - name: DOCUMENTROOT
            value: ${DOCUMENTROOT}
          - name: DYNAMICSBASEURL
            value: ${DYNAMICSBASEURL}
          - name: DYNAMICS_USERNAME
            valueFrom:
              secretKeyRef:
                name: ${API_SERVICE_NAME}${SUFFIX}-credentials
                key: username
          - name: DYNAMICS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${API_SERVICE_NAME}${SUFFIX}-credentials
                key: password
          - name: KEYCLOAK_AUTHSERVERURL
            valueFrom:
              secretKeyRef:
                name: ${NAME}${SUFFIX}
                key: keycloak-url
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                name: ${NAME}${SUFFIX}
                key: keycloak-realm
          - name: KEYCLOAK_CLIENTID
            valueFrom:
              secretKeyRef:
                name: ${NAME}${SUFFIX}
                key: keycloak-clientId
          - name: CACHE_DURATION_SECONDS
            value: ${CACHE_DURATION_SECONDS}
          image: " "
          ports:
          - containerPort: ${{PORT}}
            protocol: TCP
          readinessProbe:
            timeoutSeconds: 30
            initialDelaySeconds: 3
            httpGet:
              path: "/"
              port: ${{PORT}}
          livenessProbe:
            timeoutSeconds: 30
            initialDelaySeconds: 300
            httpGet:
              path: "/"
              port: ${{PORT}}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}${SUFFIX}
        from:
          kind: ImageStreamTag
          name: ${NAME}:${TAG_NAME}
          namespace: ${IMAGE_NAMESPACE}

parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all the objects defined in this template.
  required: true
  value: ecas-frontend
- name: SUFFIX
  displayName: Suffix
  description: A name suffix used for all objects.
  required: false
  value:
- name: APP_NAME
  displayName: App Name
  description: Used to group components together in the OpenShift console.
  required: true
  value: ecas
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: ecas
- name: APPLICATION_DOMAIN
  displayName: Application Hostname
  description: The exposed hostname that will route to the service, if left blank a value will be defaulted.
  required: false
  value: ""
- name: IMAGE_NAMESPACE
  displayName: Namespace containing application images.
  required: true
  value: pvpywj-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod.
  required: true
  value: dev
- name: APP_KEY
  displayName: Application Unique KEY
  from: "[a-zA-Z0-9]{32}"
  generate: expression
- name: API_KEY
  displayName: Unique API KEY
  from: "[a-zA-Z0-9]{32}"
  generate: expression
- name: APP_DEBUG
  displayName: Application Debug
  required: true
  value: "false"
- name: DOCUMENTROOT
  displayName: Document Root
  required: true
  value: "/public"
- name: PORT
  displayName: Port
  description: The port on which the service will listen.
  required: true
  value: "8080"
- name: DYNAMICSBASEURL
  displayName: Dynamics API
  description: The endpoint for the internal Dynamics API component.
  required: true
  value: "http://ecas-api:8080/api"
- name: API_SERVICE_NAME
  displayName: API Service Name
  description: The service name for the internal Dynamics API (ecas-api) component.
  required: true
  value: "ecas-api"
- name: KEYCLOAK_AUTHSERVERURL
  displayName: KeyCloak Authentication Server URL
  description: The URL of the KeyCloak Authentication Server.
  required: true
  value: ""
- name: KEYCLOAK_REALM
  displayName: KeyCloak Realm
  description: The KeyCloak Realm for the application.
  required: true
  value: ""
- name: KEYCLOAK_CLIENTID
  displayName: KeyCloak Client ID
  description: The KeyCloak Client ID for the application.
  required: true
  value: ""
- name: CACHE_DURATION_SECONDS
  displayName: Cache Duration Seconds
  description: The cache duration in seconds.
  required: true
  value: "28800"
- name: CPU_REQUEST
  displayName: Resources CPU Request
  description: The resources CPU request (in cores) for this build.
  required: true
  value: 10m
- name: CPU_LIMIT
  displayName: Resources CPU Limit
  description: The resources CPU limit (in cores) for this build.
  required: true
  value: 250m
- name: MEMORY_REQUEST
  displayName: Resources Memory Request
  description: The resources Memory request (in Mi, Gi, etc) for this build.
  required: true
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Resources Memory Limit
  description: The resources Memory limit (in Mi, Gi, etc) for this build.
  required: true
  value: 1Gi