---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
  spec:
    ports:
    - name: ${NAME}
      port: ${{PORT}}
      protocol: TCP
      targetPort: ${{PORT}}
    selector:
      name: ${NAME}

- kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: ${NAME}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        name: ${NAME}
        labels:
          name: ${NAME}
          app: ${APP_GROUP}
          app-group: ${APP_GROUP}
      spec:
        containers:
        - name: ${NAME}
          env:
          - name: APP_KEY
            value: ${APP_KEY}
          - name: API_KEY
            value: ${API_KEY}
          - name: APP_DEBUG
            value: ${APP_DEBUG}
          - name: DOCUMENTROOT
            value: ${DOCUMENTROOT}
          - name: DYNAMICSBASEURL
            value: ${DYNAMICSBASEURL}
          image: " "
          ports:
          - containerPort: ${{PORT}}
            protocol: TCP
          readinessProbe:
            timeoutSeconds: 30
            initialDelaySeconds: 3
            httpGet:
              path: "/"
              port: ${{PORT}}
          livenessProbe:
            timeoutSeconds: 30
            initialDelaySeconds: 300
            httpGet:
              path: "/"
              port: ${{PORT}}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:${TAG_NAME}
          namespace: ${IMAGE_NAMESPACE}

parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all the objects defined in this template.
  required: true
  value: ecas-frontend
- name: IMAGE_NAME
  displayName: Image Name
  description: The image name assigned to all the objects defined in this template.
  required: true
  value: ecas-frontend
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: ecas
- name: APPLICATION_DOMAIN
  displayName: Application Hostname
  description: The exposed hostname that will route to the service, if left blank a value will be defaulted.
  required: false
  value: ""
- name: IMAGE_NAMESPACE
  displayName: Namespace containing application images.
  required: true
  value: pvpywj-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod.
  required: true
  value: dev
- name: APP_KEY
  displayName: Application Unique KEY
  from: "[a-zA-Z0-9]{32}"
  generate: expression
- name: API_KEY
  displayName: Unique API KEY
  from: "[a-zA-Z0-9]{32}"
  generate: expression
- name: APP_DEBUG
  displayName: Application Debug
  required: true
  value: "false"
- name: DOCUMENTROOT
  displayName: Document Root
  required: true
  value: "/public"
- name: PORT
  displayName: Port
  description: The port on which the service will listen.
  required: true
  value: "8080"
- name: DYNAMICSBASEURL
  displayName: Dynamics API
  description: The endpoint for the internal Dynamics API component.
  required: true
  value: "http://ecas-api:8080/api"
- name: CPU_REQUEST
  displayName: Resources CPU Request
  description: The resources CPU request (in cores) for this build.
  required: true
  value: 10m
- name: CPU_LIMIT
  displayName: Resources CPU Limit
  description: The resources CPU limit (in cores) for this build.
  required: true
  value: 250m
- name: MEMORY_REQUEST
  displayName: Resources Memory Request
  description: The resources Memory request (in Mi, Gi, etc) for this build.
  required: true
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Resources Memory Limit
  description: The resources Memory limit (in Mi, Gi, etc) for this build.
  required: true
  value: 1Gi