---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}${SUFFIX}-deployment-template"
  creationTimestamp: 
objects:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}${SUFFIX}"
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
    annotations:
      description: Defines how to deploy ${NAME}${SUFFIX}
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}${SUFFIX}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${SOURCE_IMAGE_NAME}:${TAG_NAME}"
    replicas: 1
    selector:
      name: "${NAME}${SUFFIX}"
    template:
      metadata:
        name: "${NAME}${SUFFIX}"
        labels:
          name: ${NAME}${SUFFIX}
          app: ${APP_NAME}${SUFFIX}
          app-group: ${APP_GROUP}
      spec:
        containers:
        - name: "${NAME}${SUFFIX}"
          image: ''
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "${ASPNETCORE_ENVIRONMENT}"
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          liveinessProbe:
            httpGet:
              path: "/"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}${SUFFIX}"
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
    annotations:
      description: Exposes and load balances the application pods.
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      name: "${NAME}${SUFFIX}"
    type: ClusterIP
    sessionAffinity: None

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
    name: "${NAME}${SUFFIX}"
  spec:
    host: "${APPLICATION_DOMAIN}"
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${NAME}${SUFFIX}"
      weight: 100

- apiVersion: v1
  kind: Route
  metadata:
    name: "${NAME}${SUFFIX}-siteminder-route"
    labels:
      name: ${NAME}${SUFFIX}-siteminder-route
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
  spec:
    host: "${SITEMINDER_APPLICATION_DOMAIN}"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: "${NAME}${SUFFIX}"
      weight: 100

- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    name: "${NAME}${SUFFIX}"
    labels:
      name: ${NAME}${SUFFIX}
      app: ${APP_NAME}${SUFFIX}
      app-group: ${APP_GROUP}
  spec:
    scaleTargetRef:
      kind: DeploymentConfig
      name: "${NAME}${SUFFIX}"
    minReplicas: 2
    maxReplicas: 4

# - apiVersion: v1
#   kind: PersistentVolumeClaim
#   metadata:
#     name: "${KEY_RING_STORAGE_NAME}"
#   spec:
#     accessModes:
#     - ReadWriteOnce
#     resources:
#       requests:
#         storage: 5Gi

parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all the objects defined in this template.
  required: true
  value: cas-api
- name: SUFFIX
  displayName: Suffix
  description: A name suffix used for all objects.
  required: false
  value: 
- name: APP_NAME
  displayName: App Name
  description: Used to group components together in the OpenShift console.
  required: true
  value: ECAS
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: ecas
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the image to use for this resource.
  required: true
  value: cas-api
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: The namespace of the OpenShift project containing the imagestream for the application.
  required: true
  value: pvpywj-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: ASPNETCORE_ENVIRONMENT
  displayName: AspNetCore Environment
  description: The ASP Net Core deployment environment setting.
  required: true
  value: Production
- name: SITEMINDER_APPLICATION_DOMAIN
  description: The endpoint used for SiteMinder routed access to the application.
  displayName: SiteMinder Application Domain
  value: cas-api-pvpywj-dev.pathfinder.bcgov
- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the service, e.g., myappname.pathfinder.gov.bc.ca, if left blank a value will be defaulted.
  displayName: Application Domain
  value: cas-api-pvpywj-dev.pathfinder.gov.bc.ca
# - name: SHOW_LOGIN
#   displayName: Show login
#   description: Boolean that shows login, e.g., true, if left blank a value will be defaulted.
#   required: true
#   value: 'true'
# - name: IS_LITE_VERSION
#   description: Boolean that shows CARLA Lite, e.g., false, if left blank a value will be defaulted.
#   displayName: Is lite version
#   required: true
#   value: 'false'
# - name: DASHBOARD_LITE
#   description: Boolean that shows Dashboard Lite for CARLA lite, e.g., false, if left blank a value will be defaulted.
#   displayName: Dashboard lite
#   required: true
#   value: 'false'
# - name: SECRET_RESOURCE_NAME
#   displayName: Secret resource name
#   description: Secret resource name
#   required: true
#   value: cas-interface-service
# - name: KEY_RING_STORAGE_NAME
#   displayName: Key Ring Directory Name
#   description: Persistent storage directory name for key ring, e.g., key-ring, if left blank a value will be defaulted.
#   required: true
#   value: key-ring
- name: CPU_REQUEST
  displayName: CPU Request
  description: Starting amount of CPU the container can use.
  value: 10m
- name: CPU_LIMIT
  displayName: CPU Limit
  description: Maximum amount of CPU the container can use.
  value: 500m
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Starting amount of memory the container can use.
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi