FROM php:7.2-apache

# Add the necessary libraries and extensions to PHP
RUN apt-get update  \
    && apt-get install -y \
    libmcrypt-dev \
    curl \
    git \
    zip \
    unzip \
    default-mysql-client  libmagickwand-dev --no-install-recommends \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install zip
RUN pecl install mcrypt-1.0.5 \
    && docker-php-ext-enable mcrypt
#RUN npm i -g npm
# Set the documet root
ENV APACHE_DOCUMENT_ROOT /web-app/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Enable mod_rewrite module to make our urls work
RUN a2enmod rewrite

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


RUN mkdir /web-app 


WORKDIR /web-app

COPY ./web-app  ./
RUN rm -rf  public/css/*  public/js/* bootstrap/cache/*

RUN composer install 

USER root


RUN chmod -R go+w ./storage
RUN chmod -R go+w ./bootstrap/cache


RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN apt-get update  \
    && apt-get install -y software-properties-common npm libavahi-compat-libdnssd-dev ssh 
RUN service apache2 restart
RUN npm cache clean --force\
    && npm install 	\
	&& npm run dev 


	

