version: '3'
services:

  # ecas-frontend
  #  DYNAMICSBASEURL=https://ecaswebapi.azurewebsites.net/api
  ecas-frontend:
    image: ecas-frontend
    ports:
      - 7070:8080
    networks:
      - webnet
 
    environment:
      - APP_KEY=${APP_KEY_BASE64}
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DOCUMENTROOT=/public
      - DYNAMICSBASEURL=${DYNAMICSBASEURL:-http://ecas-api:8080/api}

  # ecas-api
  #
  ecas-api:
    image: ecas-api
    ports:
      - 8080:8080
    networks:
      - webnet

  # cas-api
  #
  cas-api:
    image: cas-api
    ports:
      - 8081:8080
    networks:
      - webnet


networks:
  webnet: